/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.proyecto1lenguajesformales2021;

import java.beans.PropertyChangeEvent;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raymond
 */
public class VistaGráfica extends javax.swing.JFrame {

    /**
     * Creates new form VistaGráfica
     */
    AnalizadorTokens analizador;
    ArchivosLeerEscribir arch;
    ReporteErrores reportError;
    java.awt.event.WindowEvent eventoInicioVentana;
    public VistaGráfica() {
        initComponents();
        inicializarVariables();
        formWindowOpeneded(eventoInicioVentana);
        formWindowOpenededTokens(eventoInicioVentana);
        formWindowOpenededrecuentoLexemas(eventoInicioVentana);
       
    }
    public void inicializarVariables(){
        analizador=new AnalizadorTokens();
        arch= new ArchivosLeerEscribir();
        reportError=new ReporteErrores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        panelPrincipal = new javax.swing.JPanel();
        labelEntradaTexto = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaEntradaTexto = new javax.swing.JTextArea();
        cargarDatos = new javax.swing.JButton();
        botonLimpiarEntrada = new javax.swing.JButton();
        botonAnalizar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        salidaResultadoArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        limpiarConsola = new javax.swing.JButton();
        botonGuardarArchivo = new javax.swing.JButton();
        fieldBuscador = new javax.swing.JTextField();
        botonBuscar = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        areaBuscador = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaErroresReportes = new javax.swing.JTable();
        panelReporteTokens = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaReportesTokens = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablaRecuentoLexemas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Analizador léxico");
        setBackground(java.awt.Color.black);
        setSize(new java.awt.Dimension(0, 0));

        jPanel1.setBackground(java.awt.Color.black);

        jTabbedPane2.setBackground(java.awt.Color.black);
        jTabbedPane2.setForeground(java.awt.Color.white);

        panelPrincipal.setBackground(java.awt.Color.darkGray);
        panelPrincipal.setForeground(java.awt.Color.white);

        labelEntradaTexto.setBackground(java.awt.Color.orange);
        labelEntradaTexto.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        labelEntradaTexto.setForeground(java.awt.Color.red);
        labelEntradaTexto.setText("Entrada de texto:");

        textAreaEntradaTexto.setBackground(new java.awt.Color(16, 53, 91));
        textAreaEntradaTexto.setColumns(20);
        textAreaEntradaTexto.setForeground(java.awt.Color.orange);
        textAreaEntradaTexto.setRows(5);
        textAreaEntradaTexto.setSelectionColor(java.awt.Color.pink);
        jScrollPane1.setViewportView(textAreaEntradaTexto);

        cargarDatos.setBackground(java.awt.SystemColor.info);
        cargarDatos.setText("Carga de datos");
        cargarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarDatosActionPerformed(evt);
            }
        });

        botonLimpiarEntrada.setBackground(new java.awt.Color(112, 24, 29));
        botonLimpiarEntrada.setForeground(java.awt.Color.white);
        botonLimpiarEntrada.setText("Limpiar Entrada");
        botonLimpiarEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimpiarEntradaActionPerformed(evt);
            }
        });

        botonAnalizar.setBackground(java.awt.SystemColor.desktop);
        botonAnalizar.setText("Analizar");
        botonAnalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAnalizarActionPerformed(evt);
            }
        });

        salidaResultadoArea.setEditable(false);
        salidaResultadoArea.setBackground(java.awt.Color.black);
        salidaResultadoArea.setColumns(20);
        salidaResultadoArea.setFont(new java.awt.Font("Noto Sans Mono", 0, 15)); // NOI18N
        salidaResultadoArea.setForeground(new java.awt.Color(43, 236, 65));
        salidaResultadoArea.setRows(5);
        jScrollPane2.setViewportView(salidaResultadoArea);

        jLabel1.setBackground(java.awt.Color.cyan);
        jLabel1.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        jLabel1.setForeground(java.awt.Color.cyan);
        jLabel1.setText("Consola");

        limpiarConsola.setBackground(javax.swing.UIManager.getDefaults().getColor("CheckBoxMenuItem.selectionBackground"));
        limpiarConsola.setForeground(java.awt.Color.orange);
        limpiarConsola.setText("Clear Consol");
        limpiarConsola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarConsolaActionPerformed(evt);
            }
        });

        botonGuardarArchivo.setText("Guardar Archivo");
        botonGuardarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarArchivoActionPerformed(evt);
            }
        });

        botonBuscar.setForeground(java.awt.Color.red);
        botonBuscar.setText("Buscar");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        areaBuscador.setColumns(20);
        areaBuscador.setRows(5);
        jScrollPane6.setViewportView(areaBuscador);

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(botonGuardarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(labelEntradaTexto))
                            .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cargarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(limpiarConsola, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(botonLimpiarEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addComponent(fieldBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 15, Short.MAX_VALUE))
                            .addComponent(jScrollPane6)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(botonAnalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(32, 32, 32))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cargarDatos)
                    .addComponent(labelEntradaTexto)
                    .addComponent(fieldBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBuscar))
                .addGap(14, 14, 14)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonLimpiarEntrada)
                    .addComponent(botonGuardarArchivo))
                .addGap(32, 32, 32)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(limpiarConsola)
                    .addComponent(botonAnalizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Funcionalidad", panelPrincipal);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Reportes de Errores"));

        tablaErroresReportes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tablaErroresReportes);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelReporteTokens.setBorder(javax.swing.BorderFactory.createTitledBorder("Reporte de tokens"));

        tablaReportesTokens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(tablaReportesTokens);

        javax.swing.GroupLayout panelReporteTokensLayout = new javax.swing.GroupLayout(panelReporteTokens);
        panelReporteTokens.setLayout(panelReporteTokensLayout);
        panelReporteTokensLayout.setHorizontalGroup(
            panelReporteTokensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1239, Short.MAX_VALUE)
        );
        panelReporteTokensLayout.setVerticalGroup(
            panelReporteTokensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Recuento de Lexemas"));

        tablaRecuentoLexemas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane5.setViewportView(tablaRecuentoLexemas);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelReporteTokens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(27, 27, 27))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(panelReporteTokens, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("REPORTES", jPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonGuardarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarArchivoActionPerformed
        guardarArchivo();
    }//GEN-LAST:event_botonGuardarArchivoActionPerformed

    private void limpiarConsolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarConsolaActionPerformed
        salidaResultadoArea.setText("");
        inicializarVariables();
    }//GEN-LAST:event_limpiarConsolaActionPerformed

    private void botonAnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAnalizarActionPerformed
        limpiarTablaErrores();
        limpiarTablaTokens();
        limpiarTablaRecuentoTokens();
        AnalizadorTokens.hayErrores=false;
        //textAreaEntradaTexto.setText(textAreaEntradaTexto.getText());
        //se debe analizar linea por linea
        //analizador.iniciarAnalizador(textAreaEntradaTexto.getText(),2);
        //salidaResultadoArea.setText(analizador.getResultadoObtenido() +"\n");
        arch.leerArchivoAnalizando(textAreaEntradaTexto.getText(), salidaResultadoArea);
        System.out.println(textAreaEntradaTexto.getText());
        //nalizador.analizarLexemas(textAreaEntradaTexto.getText());
        analizador.analizarLexemas(tablaReportesTokens,tablaRecuentoLexemas,textAreaEntradaTexto.getText());

    }//GEN-LAST:event_botonAnalizarActionPerformed

    private void botonLimpiarEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimpiarEntradaActionPerformed
        textAreaEntradaTexto.setText("");
    }//GEN-LAST:event_botonLimpiarEntradaActionPerformed
    public void limpiarTablaErrores(){
        DefaultTableModel modelo = (DefaultTableModel)tablaErroresReportes.getModel();
        for(int i=0; i<tablaErroresReportes.getRowCount();i++){
            modelo.removeRow(i);
            i-=1;
        }
    }
    public void limpiarTablaTokens(){
         DefaultTableModel modelo = (DefaultTableModel)tablaReportesTokens.getModel();
        for(int i=0; i<tablaReportesTokens.getRowCount();i++){
            modelo.removeRow(i);
            
            i-=1;
        }
    }
    public void limpiarTablaRecuentoTokens(){
        DefaultTableModel modelo=(DefaultTableModel)tablaRecuentoLexemas.getModel();
        for(int i=0; i<tablaRecuentoLexemas.getRowCount(); i++){
            modelo.removeRow(i);
            i-=1;
        }
    }
    
    private void cargarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarDatosActionPerformed
        AnalizadorTokens.hayErrores=false;
        abrirFileChooser();
         analizador.analizarLexemas(tablaReportesTokens,tablaRecuentoLexemas,textAreaEntradaTexto.getText());
    }//GEN-LAST:event_cargarDatosActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        String fRojo ="\033[31m";
        String palabra = fieldBuscador.getText()+fRojo;
        areaBuscador.setText(palabra);
        System.out.println(palabra);
    }//GEN-LAST:event_botonBuscarActionPerformed
    public static void agregarReporteError(Object row[]){
       ((DefaultTableModel) tablaErroresReportes.getModel()).addRow(row);
    }
    public static void agregarReporteToken(Object ror[]){
         ((DefaultTableModel) tablaReportesTokens.getModel()).addRow(ror);
    }
    
   
    /**
     * @param args the command line arguments
     */
  
    public void abrirFileChooser(){
        JFileChooser jf= new JFileChooser();
        jf.showOpenDialog(this);
        File archivo = jf.getSelectedFile();
        textAreaEntradaTexto.setText("");
        limpiarTablaTokens();
        limpiarTablaErrores();
        limpiarTablaRecuentoTokens();
        if(archivo !=null || !archivo.getName().equals("")){           
            salidaResultadoArea.setText(archivo.getAbsolutePath());
            arch.leerArchivoDeEntrada(archivo.getAbsolutePath(),textAreaEntradaTexto,salidaResultadoArea);               
        }
        
    }
    public void guardarArchivo(){
        JFileChooser guardar = new JFileChooser();
        guardar.setApproveButtonText("Guardar");
        guardar.showSaveDialog(null);
        arch.guardarArchivo(textAreaEntradaTexto.getText(),guardar.getSelectedFile().toString());
    }
    private void formWindowOpeneded(java.awt.event.WindowEvent event){
        DefaultTableModel modelo = (DefaultTableModel)tablaErroresReportes.getModel();
        modelo.addColumn("Token");
        modelo.addColumn("Fila");
        modelo.addColumn("Columna");
    }
     private void formWindowOpenededTokens(java.awt.event.WindowEvent event){
        DefaultTableModel modelo = (DefaultTableModel)tablaReportesTokens.getModel();
        modelo.addColumn("Lexema");
        modelo.addColumn("Token");
        modelo.addColumn("Fila");
        modelo.addColumn("Columna");
    }
      private void formWindowOpenededrecuentoLexemas(java.awt.event.WindowEvent event){
        DefaultTableModel modelo = (DefaultTableModel)tablaRecuentoLexemas.getModel();
        modelo.addColumn("Lexema");
        modelo.addColumn("Token");
        modelo.addColumn("Cantidad");
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaBuscador;
    private javax.swing.JButton botonAnalizar;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonGuardarArchivo;
    private javax.swing.JButton botonLimpiarEntrada;
    private javax.swing.JButton cargarDatos;
    private javax.swing.JTextField fieldBuscador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel labelEntradaTexto;
    private javax.swing.JButton limpiarConsola;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelReporteTokens;
    private javax.swing.JTextArea salidaResultadoArea;
    public static javax.swing.JTable tablaErroresReportes;
    private javax.swing.JTable tablaRecuentoLexemas;
    public static javax.swing.JTable tablaReportesTokens;
    private javax.swing.JTextArea textAreaEntradaTexto;
    // End of variables declaration//GEN-END:variables

}
