/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.proyecto1lenguajesformales2021;

import java.beans.PropertyChangeEvent;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raymond
 */
public class VistaGráfica extends javax.swing.JFrame {

    /**
     * Creates new form VistaGráfica
     */
    AnalizadorTokens analizador;
    ArchivosLeerEscribir arch;
    java.awt.event.WindowEvent eventoInicioVentana;
    public VistaGráfica() {
        initComponents();
        inicializarVariables();
        formWindowOpeneded(eventoInicioVentana);
        formWindowTablaTokens(eventoInicioVentana);
       
    }
    public void inicializarVariables(){
        analizador=new AnalizadorTokens();
        arch= new ArchivosLeerEscribir();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        panelPrincipal = new javax.swing.JPanel();
        labelEntradaTexto = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaEntradaTexto = new javax.swing.JTextArea();
        cargarDatos = new javax.swing.JButton();
        botonLimpiarEntrada = new javax.swing.JButton();
        botonAnalizar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        salidaResultadoArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        limpiarConsola = new javax.swing.JButton();
        botonGuardarArchivo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Analizador léxico");
        setBackground(java.awt.Color.black);
        setSize(new java.awt.Dimension(0, 0));

        jPanel1.setBackground(java.awt.Color.black);

        jTabbedPane2.setBackground(java.awt.Color.black);
        jTabbedPane2.setForeground(java.awt.Color.white);

        panelPrincipal.setBackground(java.awt.Color.darkGray);
        panelPrincipal.setForeground(java.awt.Color.white);

        labelEntradaTexto.setBackground(java.awt.Color.orange);
        labelEntradaTexto.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        labelEntradaTexto.setForeground(java.awt.Color.red);
        labelEntradaTexto.setText("Entrada de texto:");

        textAreaEntradaTexto.setBackground(new java.awt.Color(16, 53, 91));
        textAreaEntradaTexto.setColumns(20);
        textAreaEntradaTexto.setForeground(java.awt.Color.orange);
        textAreaEntradaTexto.setRows(5);
        textAreaEntradaTexto.setSelectionColor(java.awt.Color.pink);
        jScrollPane1.setViewportView(textAreaEntradaTexto);

        cargarDatos.setBackground(java.awt.SystemColor.info);
        cargarDatos.setText("Carga de datos");
        cargarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarDatosActionPerformed(evt);
            }
        });

        botonLimpiarEntrada.setBackground(new java.awt.Color(112, 24, 29));
        botonLimpiarEntrada.setForeground(java.awt.Color.white);
        botonLimpiarEntrada.setText("Limpiar");
        botonLimpiarEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimpiarEntradaActionPerformed(evt);
            }
        });

        botonAnalizar.setBackground(java.awt.SystemColor.desktop);
        botonAnalizar.setText("Analizar");
        botonAnalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAnalizarActionPerformed(evt);
            }
        });

        salidaResultadoArea.setEditable(false);
        salidaResultadoArea.setBackground(java.awt.Color.black);
        salidaResultadoArea.setColumns(20);
        salidaResultadoArea.setFont(new java.awt.Font("Noto Sans Mono", 0, 15)); // NOI18N
        salidaResultadoArea.setForeground(new java.awt.Color(43, 236, 65));
        salidaResultadoArea.setRows(5);
        jScrollPane2.setViewportView(salidaResultadoArea);

        jLabel1.setBackground(java.awt.Color.cyan);
        jLabel1.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        jLabel1.setForeground(java.awt.Color.cyan);
        jLabel1.setText("Consola");

        limpiarConsola.setBackground(javax.swing.UIManager.getDefaults().getColor("CheckBoxMenuItem.selectionBackground"));
        limpiarConsola.setForeground(java.awt.Color.orange);
        limpiarConsola.setText("Clear Consol");
        limpiarConsola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarConsolaActionPerformed(evt);
            }
        });

        botonGuardarArchivo.setText("Guardar Archivo");
        botonGuardarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarArchivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(labelEntradaTexto)
                .addGap(394, 394, 394)
                .addComponent(cargarDatos, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                .addGap(32, 32, 32))
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(botonGuardarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonLimpiarEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonAnalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(limpiarConsola, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 772, Short.MAX_VALUE))
                .addGap(32, 32, 32))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cargarDatos)
                    .addComponent(labelEntradaTexto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonLimpiarEntrada)
                    .addComponent(botonAnalizar)
                    .addComponent(botonGuardarArchivo))
                .addGap(32, 32, 32)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(limpiarConsola))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(179, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Funcionalidad", panelPrincipal);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 836, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonGuardarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarArchivoActionPerformed
        guardarArchivo();
    }//GEN-LAST:event_botonGuardarArchivoActionPerformed

    private void limpiarConsolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarConsolaActionPerformed
        salidaResultadoArea.setText("");
        inicializarVariables();
    }//GEN-LAST:event_limpiarConsolaActionPerformed

    private void botonAnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAnalizarActionPerformed
        //textAreaEntradaTexto.setText(textAreaEntradaTexto.getText());
        //se debe analizar linea por linea
        //analizador.iniciarAnalizador(textAreaEntradaTexto.getText(),2);
        //salidaResultadoArea.setText(analizador.getResultadoObtenido() +"\n");
        arch.leerArchivoAnalizando(textAreaEntradaTexto.getText(), salidaResultadoArea);
        System.out.println(textAreaEntradaTexto.getText());

    }//GEN-LAST:event_botonAnalizarActionPerformed

    private void botonLimpiarEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimpiarEntradaActionPerformed
        textAreaEntradaTexto.setText("");
    }//GEN-LAST:event_botonLimpiarEntradaActionPerformed

    private void cargarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarDatosActionPerformed
        abrirFileChooser();
    }//GEN-LAST:event_cargarDatosActionPerformed

   
    /**
     * @param args the command line arguments
     */
  
    public void abrirFileChooser(){
        JFileChooser jf= new JFileChooser();
        jf.showOpenDialog(this);
        File archivo = jf.getSelectedFile();
        if(archivo !=null || !archivo.getName().equals("")){           
            salidaResultadoArea.setText(archivo.getAbsolutePath());
            arch.leerArchivoDeEntrada(archivo.getAbsolutePath(),textAreaEntradaTexto,salidaResultadoArea);               
        }
    }
    public void guardarArchivo(){
        JFileChooser guardar = new JFileChooser();
        guardar.setApproveButtonText("Guardar");
        guardar.showSaveDialog(null);
        arch.guardarArchivo(textAreaEntradaTexto.getText(),guardar.getSelectedFile().toString());
    }
    private void formWindowOpeneded(java.awt.event.WindowEvent event){
        DefaultTableModel modelo = (DefaultTableModel)tablaReportesErrores.getModel();
        modelo.addColumn("Token");
        modelo.addColumn("Fila");
        modelo.addColumn("Columna");
    }
     private void formWindowTablaTokens(java.awt.event.WindowEvent event){
        DefaultTableModel modelo = (DefaultTableModel)TablaReportesTokens.getModel();
        modelo.addColumn("Token");
        modelo.addColumn("Fila");
        modelo.addColumn("Columna");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAnalizar;
    private javax.swing.JButton botonGuardarArchivo;
    private javax.swing.JButton botonLimpiarEntrada;
    private javax.swing.JButton cargarDatos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel labelEntradaTexto;
    private javax.swing.JButton limpiarConsola;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JTextArea salidaResultadoArea;
    private javax.swing.JTextArea textAreaEntradaTexto;
    // End of variables declaration//GEN-END:variables

}
